### ISSUE TITLE
Symfony 4 - refresh services definitions

### ISSUE THREAD

**Issue by mbdax034** [TheNouillet/symfony-vscode#36] opened 2019-04-07 10:48 UTC
Hello,
Thank you for this plugin . I got this error when i refresh services definitions 

PHP Fatal error:  Cannot use Riak\Object as Object because 'Object' is a special class name in .../vendor/doctrine/cache/lib/Doctrine/Common/Cache/RiakCache.php on line 8
12:44:35 CRITICAL  [php] Fatal Compile Error: Cannot use Riak\Object as Object because 'Object' is a special class name ["exception" => Symfony\Component\Debug\Exception\FatalErrorException { …}]

In RiakCache.php line 8:
                                                                               
  Compile Error: Cannot use Riak\Object as Object because 'Object' is a speci  
  al class name                                                                
                                                                               

debug:container [--show-private] [--show-arguments] [--show-hidden] [--tag TAG] [--tags] [--parameter PARAMETER] [--parameters] [--types] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]

**Comment by TheNouillet** [comment] 2019-04-15 12:13
Hello,

This issue is a duplicate of #30, so I'm going to close it. I'm working on the next release, and the goal of this version is to not rely on the console, so errors like this one will hopefully be reduced.

**Closed as completed by TheNouillet** 2019-04-15 12:13 UTC
