### ISSUE TITLE
the plugin does not initiate

### ISSUE THREAD

**Issue by zskiredj** [TheNouillet/symfony-vscode#26] opened 2019-02-22 17:05 UTC
the plugin does not work. 

It stays stucked on "Symfony is reading".

I have used :
`"symfony-vscode.phpPath": "C:/wamp/bin/php/php7.1.26/"`

Any idea why ?

**Comment by TheNouillet** [comment] 2019-02-25 00:02
Hello,

A new version of the extension has been pushed. Try upgrading and tell me if any error message showed up.

2 possibilities :

* It's because you are on a Windows system. I will soon do a check to see if the extension properly work on Windows.
* Or your project doesn't have `symfony/symfony` as one of its dependencies. The last version of the extension include `symfony/framework-bundle` as a discriminating dependency for the extension to activate.

**Comment by zskiredj** [comment] 2019-02-25 15:06
Indeed the extension works on mac, but not on Windows.

I installed it in a mac and windows 7 with same project. It works on mac but not on windows.

When do you think it will be available for windows? 

Thanks in advance.

**Comment by smertelny** [comment] 2019-02-26 10:38
Had the same problem on Windows 10, fixed by changing src/symfony/ComposerJSON file from
`let composerObj = JSON.parse(fs.readFileSync(uri.path).toString());`
to next
`let composerObj = JSON.parse(fs.readFileSync(uri.fsPath).toString());`
Don't have much time for a proper PR. If I will have time - will make it (if it will be needed).
But I can't test this on Mac.

**Comment by zskiredj** [comment] 2019-02-26 11:13
when you say 

> src/symfony/ComposerJSON

, is it in the vendor folder, or somewhere else ?

can you give the path of this file for symfony 3.4 ? thanks in advance

**Comment by smertelny** [comment] 2019-02-26 11:15
> when you say
> 
> > src/symfony/ComposerJSON
> 
> , is it in the vendor folder, or somewhere else ?
> 
> can you give the path of this file for symfony 3.4 ? thanks in advance

The problem is - that is the path in VS Code extension. So you just need to wait for a path or dig into  extension code on your local machine

**Comment by TheNouillet** [comment] 2019-02-26 21:17
Hello

@smertelny 's PR has been merged, along with additional fixes. You can update your extension and see if it works.

**Closed** 2019-04-15 12:29 UTC
